import type { PublicCreator, PublicListing } from "./types";

const now = "2026-07-05T00:00:00.000Z";

export const sampleCreators: PublicCreator[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    slug: "sample-jeju-jiyun",
    displayName: "제주한바퀴",
    bio: "제주 명소, 로컬 공간, 여행 코스와 지역 브랜드를 따뜻한 여행 영상으로 소개하는 예시 크리에이터입니다.",
    avatarPath: "/images/samples/avatar-jeju.svg",
    socialLinks: {
      youtube: "https://youtube.com/@sample-jeju-hanbakwi",
      instagram: "https://instagram.com/sample.jeju.hanbakwi",
    },
    status: "published",
    isSample: true,
    isFounding: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    slug: "sample-style-mina",
    displayName: "오늘의제주",
    bio: "카페, 패션, 일상과 로컬 공간을 자연스럽게 기록하는 제주 라이프스타일 예시 크리에이터입니다.",
    avatarPath: "/images/samples/avatar-style.svg",
    socialLinks: {
      instagram: "https://instagram.com/sample.today.jeju",
      tiktok: "https://tiktok.com/@sample.today.jeju",
    },
    status: "published",
    isSample: true,
    isFounding: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    slug: "sample-home-joon",
    displayName: "살림의기록",
    bio: "집, 생활용품, 인테리어를 직접 사용하고 꼼꼼하게 소개하는 예시 크리에이터입니다.",
    avatarPath: "/images/samples/avatar-home.svg",
    socialLinks: {
      blog: "https://blog.naver.com/sample-salim-record",
      youtube: "https://youtube.com/@sample-salim-record",
    },
    status: "published",
    isSample: true,
    isFounding: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    slug: "sample-food-sora",
    displayName: "한입서울",
    bio: "서울 맛집, 음식, 간편식을 빠르고 직관적인 숏폼과 사진으로 소개하는 예시 크리에이터입니다.",
    avatarPath: "/images/samples/avatar-food.svg",
    socialLinks: {
      tiktok: "https://tiktok.com/@sample.hanip.seoul",
      instagram: "https://instagram.com/sample.hanip.seoul",
    },
    status: "published",
    isSample: true,
    isFounding: false,
    createdAt: now,
    updatedAt: now,
  },
];

const creatorBySlug = new Map(
  sampleCreators.map((creator) => [creator.slug, creator]),
);

function creator(slug: string) {
  const found = creatorBySlug.get(slug);

  if (!found) {
    throw new Error(`Missing sample creator: ${slug}`);
  }

  return found;
}

export const sampleListings: PublicListing[] = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    slug: "sample-jeju-youtube-30s",
    title: "제주 여행 영상 내 30초 브랜드 소개",
    platform: "YouTube",
    channelName: "제주한바퀴",
    channelUrl: "https://youtube.com/@sample-jeju-hanbakwi",
    audienceSize: 82000,
    adFormat: "영상 내 30초 소개",
    description: "제주 여행 영상 흐름 안에서 브랜드, 공간, 상품을 약 30초간 자연스럽게 소개합니다.",
    deliverables: ["영상 내 30초 소개", "고정 댓글 7일 유지", "간단한 집행 결과 공유"],
    priceKrw: 500000,
    imagePaths: ["/images/samples/jeju-hanbakwi-youtube-integration.webp"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-jeju-jiyun"),
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    slug: "sample-jeju-youtube-dedicated",
    title: "제주 로컬 브랜드 단독 리뷰 영상",
    platform: "YouTube",
    channelName: "제주한바퀴",
    channelUrl: "https://youtube.com/@sample-jeju-hanbakwi",
    audienceSize: 82000,
    adFormat: "단독 리뷰 영상",
    description: "하나의 제주 로컬 브랜드나 공간을 중심으로 제작하는 단독 YouTube 리뷰 콘텐츠입니다.",
    deliverables: ["단독 리뷰 영상 1편", "영상 설명란 링크 삽입", "콘텐츠 내 핵심 포인트 소개"],
    priceKrw: 1200000,
    imagePaths: ["/images/samples/jeju-hanbakwi-youtube-review.webp"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-jeju-jiyun"),
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    slug: "sample-style-instagram-reels",
    title: "제주 라이프스타일 Instagram 릴스 1편",
    platform: "Instagram",
    channelName: "오늘의제주",
    channelUrl: "https://instagram.com/sample.today.jeju",
    audienceSize: 54000,
    adFormat: "릴스 1편",
    description: "제품, 공간, 서비스를 자연스러운 제주 라이프스타일 콘텐츠로 제작합니다.",
    deliverables: ["릴스 1편 제작", "피드 30일 유지", "브랜드 계정 태그"],
    priceKrw: 350000,
    imagePaths: ["/images/samples/today-jeju-instagram-reels.webp"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-style-mina"),
  },
  {
    id: "10000000-0000-4000-8000-000000000004",
    slug: "sample-style-instagram-story",
    title: "Instagram 스토리 3컷 소개",
    platform: "Instagram",
    channelName: "오늘의제주",
    channelUrl: "https://instagram.com/sample.today.jeju",
    audienceSize: 54000,
    adFormat: "스토리 3컷",
    description: "직접 사용하거나 방문한 모습을 3개의 연속 스토리로 소개합니다.",
    deliverables: ["스토리 3컷 업로드", "링크 스티커 포함", "24시간 노출 캡처 제공"],
    priceKrw: 180000,
    imagePaths: ["/images/samples/today-jeju-instagram-story.webp"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-style-mina"),
  },
  {
    id: "10000000-0000-4000-8000-000000000005",
    slug: "sample-home-blog-review",
    title: "생활용품 네이버 블로그 상세 리뷰",
    platform: "네이버 블로그",
    channelName: "살림의기록",
    channelUrl: "https://blog.naver.com/sample-salim-record",
    audienceSize: 36000,
    adFormat: "상세 리뷰 포스트",
    description: "직접 사용한 과정과 사진을 포함하는 상세 리뷰형 블로그 포스트입니다.",
    deliverables: ["블로그 리뷰 1건", "사진 8장 이상", "검색 키워드 3개 반영"],
    priceKrw: 420000,
    imagePaths: ["/images/samples/salim-record-naver-blog-review.webp"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-home-joon"),
  },
  {
    id: "10000000-0000-4000-8000-000000000006",
    slug: "sample-home-youtube-shorts",
    title: "집과 생활 YouTube Shorts 1편",
    platform: "YouTube",
    channelName: "살림의기록",
    channelUrl: "https://youtube.com/@sample-salim-record",
    audienceSize: 41000,
    adFormat: "Shorts 1편",
    description: "제품이나 서비스를 짧고 직관적인 세로형 영상으로 소개합니다.",
    deliverables: ["Shorts 1편 제작", "핵심 사용 장면 소개", "설명란 링크 삽입"],
    priceKrw: 280000,
    imagePaths: ["/images/samples/salim-record-youtube-shorts.webp"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-home-joon"),
  },
  {
    id: "10000000-0000-4000-8000-000000000007",
    slug: "sample-food-tiktok-quick",
    title: "음식·간편식 TikTok 20초 숏폼",
    platform: "TikTok",
    channelName: "한입서울",
    channelUrl: "https://tiktok.com/@sample.hanip.seoul",
    audienceSize: 73000,
    adFormat: "20초 숏폼",
    description: "음식의 특징과 먹는 장면을 빠른 템포로 보여주는 짧은 영상입니다.",
    deliverables: ["20초 TikTok 영상 1편", "브랜드 해시태그 포함", "댓글 반응 캡처 제공"],
    priceKrw: 300000,
    imagePaths: ["/images/samples/hanip-seoul-tiktok-shortform.webp"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-food-sora"),
  },
  {
    id: "10000000-0000-4000-8000-000000000008",
    slug: "sample-food-instagram-post",
    title: "서울 맛집 Instagram 피드 소개",
    platform: "Instagram",
    channelName: "한입서울",
    channelUrl: "https://instagram.com/sample.hanip.seoul",
    audienceSize: 48000,
    adFormat: "피드 사진 1건",
    description: "음식과 공간을 사진 중심의 Instagram 피드 콘텐츠로 소개합니다.",
    deliverables: ["피드 게시물 1건", "사진 5장 이상", "브랜드 위치 태그"],
    priceKrw: 260000,
    imagePaths: ["/images/samples/hanip-seoul-instagram-feed.webp"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-food-sora"),
  },
];
