import type { PublicCreator, PublicListing } from "./types";

const now = "2026-07-05T00:00:00.000Z";

export const sampleCreators: PublicCreator[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    slug: "sample-jeju-jiyun",
    displayName: "김지윤",
    bio: "제주 여행과 로컬 맛집을 기록하는 예시 크리에이터입니다.",
    avatarPath: "/images/samples/avatar-jeju.svg",
    socialLinks: {
      youtube: "https://youtube.com/@sample-jeju-jiyun",
      instagram: "https://instagram.com/sample.jeju.jiyun",
    },
    status: "published",
    isSample: true,
    isFounding: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    slug: "sample-style-mina",
    displayName: "박미나",
    bio: "데일리 패션과 뷰티 숏폼을 만드는 예시 크리에이터입니다.",
    avatarPath: "/images/samples/avatar-style.svg",
    socialLinks: {
      instagram: "https://instagram.com/sample.style.mina",
      tiktok: "https://tiktok.com/@sample.style.mina",
    },
    status: "published",
    isSample: true,
    isFounding: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    slug: "sample-home-joon",
    displayName: "이준호",
    bio: "집 꾸미기와 생활용품 리뷰를 다루는 예시 크리에이터입니다.",
    avatarPath: "/images/samples/avatar-home.svg",
    socialLinks: {
      blog: "https://blog.naver.com/sample-home-joon",
      youtube: "https://youtube.com/@sample-home-joon",
    },
    status: "published",
    isSample: true,
    isFounding: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    slug: "sample-food-sora",
    displayName: "최소라",
    bio: "서울 맛집과 간편식을 소개하는 예시 크리에이터입니다.",
    avatarPath: "/images/samples/avatar-food.svg",
    socialLinks: {
      tiktok: "https://tiktok.com/@sample.food.sora",
      instagram: "https://instagram.com/sample.food.sora",
    },
    status: "published",
    isSample: true,
    isFounding: false,
    createdAt: now,
    updatedAt: now,
  },
];

const creatorBySlug = new Map(
  sampleCreators.map((creator) => [creator.slug, creator]),
);

function creator(slug: string) {
  const found = creatorBySlug.get(slug);

  if (!found) {
    throw new Error(`Missing sample creator: ${slug}`);
  }

  return found;
}

export const sampleListings: PublicListing[] = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    slug: "sample-jeju-youtube-30s",
    title: "제주 여행 영상 내 30초 브랜드 소개",
    platform: "YouTube",
    channelName: "지윤의 제주 노트",
    channelUrl: "https://youtube.com/@sample-jeju-jiyun",
    audienceSize: 82000,
    adFormat: "영상 내 30초 소개",
    description: "제주 여행 브이로그 본문 흐름 안에서 브랜드를 자연스럽게 소개합니다.",
    deliverables: ["영상 내 30초 브랜드 언급", "고정 댓글 7일 유지", "간단한 집행 결과 공유"],
    priceKrw: 500000,
    imagePaths: [
      "/images/samples/jeju-youtube-1.svg",
      "/images/samples/jeju-youtube-2.svg",
      "/images/samples/jeju-youtube-3.svg",
    ],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-jeju-jiyun"),
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    slug: "sample-jeju-youtube-dedicated",
    title: "제주 로컬 브랜드 단독 리뷰 영상",
    platform: "YouTube",
    channelName: "지윤의 제주 노트",
    channelUrl: "https://youtube.com/@sample-jeju-jiyun",
    audienceSize: 82000,
    adFormat: "단독 리뷰 영상",
    description: "제주 기반 브랜드 또는 여행 상품을 하나의 영상 주제로 다룹니다.",
    deliverables: ["6분 이상 단독 리뷰 영상", "영상 설명란 링크 삽입", "썸네일 브랜드 노출"],
    priceKrw: 1200000,
    imagePaths: ["/images/samples/jeju-review-1.svg", "/images/samples/jeju-review-2.svg"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-jeju-jiyun"),
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    slug: "sample-style-instagram-reels",
    title: "봄 데일리룩 Instagram 릴스 소개",
    platform: "Instagram",
    channelName: "mina.daily",
    channelUrl: "https://instagram.com/sample.style.mina",
    audienceSize: 54000,
    adFormat: "릴스 1편",
    description: "패션 또는 뷰티 아이템을 착용 장면 중심의 릴스로 소개합니다.",
    deliverables: ["릴스 1편 제작", "피드 30일 유지", "브랜드 계정 태그"],
    priceKrw: 350000,
    imagePaths: ["/images/samples/style-reels-1.svg", "/images/samples/style-reels-2.svg"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-style-mina"),
  },
  {
    id: "10000000-0000-4000-8000-000000000004",
    slug: "sample-style-instagram-story",
    title: "Instagram 스토리 3컷 체험 소개",
    platform: "Instagram",
    channelName: "mina.daily",
    channelUrl: "https://instagram.com/sample.style.mina",
    audienceSize: 54000,
    adFormat: "스토리 3컷",
    description: "제품 사용 전후와 핵심 장점을 짧은 스토리 흐름으로 소개합니다.",
    deliverables: ["스토리 3컷 업로드", "링크 스티커 포함", "24시간 노출 캡처 제공"],
    priceKrw: 180000,
    imagePaths: ["/images/samples/style-story-1.svg"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-style-mina"),
  },
  {
    id: "10000000-0000-4000-8000-000000000005",
    slug: "sample-home-blog-review",
    title: "네이버 블로그 생활용품 상세 리뷰",
    platform: "네이버 블로그",
    channelName: "준호의 집 사용기",
    channelUrl: "https://blog.naver.com/sample-home-joon",
    audienceSize: 36000,
    adFormat: "상세 리뷰 포스트",
    description: "생활용품의 사용 장면, 장단점, 구매 포인트를 긴 글과 사진으로 정리합니다.",
    deliverables: ["블로그 리뷰 1건", "사진 8장 이상", "검색 키워드 3개 반영"],
    priceKrw: 420000,
    imagePaths: ["/images/samples/home-blog-1.svg", "/images/samples/home-blog-2.svg"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-home-joon"),
  },
  {
    id: "10000000-0000-4000-8000-000000000006",
    slug: "sample-home-youtube-shorts",
    title: "집꾸미기 YouTube Shorts 노출",
    platform: "YouTube",
    channelName: "준호의 집 사용기",
    channelUrl: "https://youtube.com/@sample-home-joon",
    audienceSize: 41000,
    adFormat: "Shorts 1편",
    description: "공간 변화 전후를 중심으로 생활용품을 짧고 명확하게 보여줍니다.",
    deliverables: ["Shorts 1편 제작", "제품명 자막 노출", "설명란 링크 삽입"],
    priceKrw: 280000,
    imagePaths: ["/images/samples/home-shorts-1.svg"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-home-joon"),
  },
  {
    id: "10000000-0000-4000-8000-000000000007",
    slug: "sample-food-tiktok-quick",
    title: "TikTok 간편식 20초 맛보기",
    platform: "TikTok",
    channelName: "sora.quickbite",
    channelUrl: "https://tiktok.com/@sample.food.sora",
    audienceSize: 73000,
    adFormat: "20초 숏폼",
    description: "간편식의 조리 과정과 첫 인상을 빠르게 보여주는 숏폼 광고입니다.",
    deliverables: ["20초 TikTok 영상 1편", "브랜드 해시태그 포함", "댓글 반응 캡처 제공"],
    priceKrw: 300000,
    imagePaths: ["/images/samples/food-tiktok-1.svg", "/images/samples/food-tiktok-2.svg"],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-food-sora"),
  },
  {
    id: "10000000-0000-4000-8000-000000000008",
    slug: "sample-food-instagram-post",
    title: "서울 맛집 Instagram 피드 소개",
    platform: "Instagram",
    channelName: "sora.quickbite",
    channelUrl: "https://instagram.com/sample.food.sora",
    audienceSize: 48000,
    adFormat: "피드 사진 1건",
    description: "방문 경험을 기반으로 메뉴와 매장 분위기를 이미지 중심으로 소개합니다.",
    deliverables: ["피드 게시물 1건", "사진 5장 이상", "브랜드 위치 태그"],
    priceKrw: 260000,
    imagePaths: [
      "/images/samples/food-feed-1.svg",
      "/images/samples/food-feed-2.svg",
      "/images/samples/food-feed-3.svg",
    ],
    status: "published",
    isSample: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    creator: creator("sample-food-sora"),
  },
];
